services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      # Defaults to localhost if DOCKER_BIND_IP isn't set
      - "${DOCKER_BIND_IP:-127.0.0.1}:5432:5432"
      - "${DOCKER_BIND_IP:-127.0.0.1}:8080:8080"
      - "${DOCKER_BIND_IP:-127.0.0.1}:1883:1883"
      - "${DOCKER_BIND_IP:-127.0.0.1}:9001:9001"
      - "${DOCKER_BIND_IP:-127.0.0.1}:8883:8883"
      - "${DOCKER_BIND_IP:-127.0.0.1}:9002:9002"
    environment:
      POSTGRES_PASSWORD: postgres
    # Mount a volume for persistence if we wanted, but not for now.

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    volumes:
      - ./docker/postgres_exporter/queries.yaml:/queries.yaml:ro
    command:
      - "--extend.query-path=/queries.yaml"
      - "--disable-default-metrics"
      - "--disable-settings-metrics"
    ports:
      - "${DOCKER_BIND_IP:-127.0.0.1}:9187:9187"
    depends_on:
      - postgres
