apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-uid
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      httpMethod: POST
      tlsSkipVerify: true
